### ISSUE TITLE
Multiple Providers Terraform - DNS Zones

### ISSUE THREAD

**Issue by zayanic** [hashicorp/terraform-provider-dns#132]
I`am creating a dns zone in azure, and a contingency zone in gcp, and the same record that will be created in azure, will be created in gcp, in a production environment that is considered a good practice, even if my code can has more than 5000 lines.
What I am doing is right, I will have no problems in the future with this, could anyone tell me if I am right or wrong to do this?

I`m using Terraform v0.14.7

provider “google” {
credentials = file(var.credentials)
project       = var.dns_zone.project_id
}

provider “azurerm” {
features {}
}

resource “azurerm_dns_zone” “test” {
name                            = “proc.com.br”
resource_group_name = var.resource_group_name
}

resource “google_dns_managed_zone” “test-dev” {
name           = “proc-zone”
dns_name    = “proc.com.br.”
description  = “DNS zone for the example domain”
}

resource “azurerm_dns_cname_record” “test” {
name                           = “cloud”
zone_name                  = azurerm_dns_zone.test.name
resource_group_name = var.resource_group_name
ttl                                  = 3600
record                           = “contoso.com.br”
}

resource “google_dns_record_set” “a_test” {
name                       = “foo.proc.com.br.”
managed_zone       = google_dns_managed_zone.test-dev.name
type                         = “CNAME”
ttl                             = 3600
rrdatas                     = [“contoso.com.br.”]
}

**Comment by bodgit** [comment]
These resources aren't anything to do with this provider.

**Comment by bflad** [comment]
Hi @zayanic 👋 Thanks for raising this.

It sounds like you could be looking for [Terraform Module](https://developer.hashicorp.com/terraform/language/modules) functionality to better manage your Terraform configuration. Using a module, you could potentially reduce your overall configuration to where the module will handle creating the records across both providers at the same time, then calling the module for each DNS record. That said, there are are sometimes downsides to an approach like that, such as a vendor outage making it more difficult to apply Terraform changes. The maintainers of this particular provider cannot provide specific guidance for you though.

As mentioned above, any resources not prefixed with `dns_` are from other providers and this issue tracker is specifically for the [`hashicorp/dns` provider](https://registry.terraform.io/providers/hashicorp/dns) so I'm going to close this out since it does not appear to be a bug or feature for this provider. If you have further general questions about your Terraform configuration, please reach out [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27) where there are more practitioners asking and answering topics, rather than these GitHub issue trackers which are typically for bug reports and feature requests.
